heat_template_version: 2021-04-16

parameters:
    flavor:
        type: string
    image:
        type: string
    network:
        type: string
    subnet:
        type: string
    secgroup:
        type: string
    wc_notify:
        type: string
    pool:
        type: string
    host_port:
        type: number
    api_branch:
        type: string

resources:
    server:
        type: OS::Nova::Server
        properties:
            flavor: { get_param: flavor }
            image: { get_param: image }
            networks:
            - { subnet: { get_param: subnet }}
            security_groups:
            - { get_param: secgroup }

            user_data_format: RAW
            user_data:
                str_replace:
                    template: { get_file: userdata.sh }
                    params:
                        $branch: { get_param: api_branch }
                        $wc_notify: { get_param: wc_notify }

    pool_member:
        type: OS::Octavia::PoolMember
        properties:
            pool: { get_param: pool }
            address: { get_attr: [server, first_address] }
            protocol_port: { get_param: host_port }
