heat_template_version: 2021-04-16

parameters:
    flavor:
        type: string
    image:
        type: string
    availability_zone:
        type: string
    network:
        type: string
    subnet:
        type: string
    secgroup:
        type: string
    wc_notify:
        type: string
    pool:
        type: string
    host_port:
        type: number
    api_branch:
        type: string
    logstash_host:
        type: string
    environment:
        type: string

resources:
    cloud_init:
        type: cloud-init.yaml
        properties:
            logstash_host: { get_param: logstash_host }
            api_branch: { get_param: api_branch }
            wc_notify: { get_param: wc_notify }
            environment: { get_param: environment }

    server:
        type: OS::Nova::Server
        properties:
            flavor: { get_param: flavor }
            image: { get_param: image }
            availability_zone: { get_param: availability_zone }
            networks:
            - { subnet: { get_param: subnet }}
            security_groups:
            - { get_param: secgroup }

            user_data_format: SOFTWARE_CONFIG
            user_data:
                get_attr: [cloud_init, cloud_config]

    pool_member:
        type: OS::Octavia::PoolMember
        properties:
            pool: { get_param: pool }
            address: { get_attr: [server, first_address] }
            protocol_port: { get_param: host_port }
